---
baseURL: "https://CasaRuralIsabel.com"
title: Web de Casa Rural Isabel
theme: gohugo-theme-ananke

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
GoogleAnalytics: false

relativeURLs: true

minify:
  disableXML: true
  minifyOutput: true

pagination:
  pagerSize: 5

params:
  mainSections: [blog]
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Casa Rural Isabel
  # description: ""
  keywords: [Blog]
  author: Casa Rural Isabel
  # author: ["Me", "You"] # multiple authors
  images: []
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  responsiveImages: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  searchHidden: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    disableFingerprinting: true

  label:
    text: "Home"
    icon: /apple-icon-152x152.png
    iconHeight: 35

  # home-info mode
  # homeInfoParams:
  # Title: "Hi!"
  # Content: Welcome to my blog

  # analytics:
  #   google:
  #     SiteVerificationTag: ""
  #   yandex:
  #     SiteVerificationTag: ""

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: home
      name: 🏠 Inicio
      url: /
      weight: 10
    - identifier: About
      name: 🗒️La casa
      url: /about/
      weight: 15

outputs:
  home: ["HTML", "RSS", "JSON"]
  page: ["HTML"]

sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"
  priority: 0.5

permalinks:
  posts: /:year/:month/:day/:title/
  /: /:year/:month/:day/:title/
  blog: /blog/:year/:month/:day/:title/

outputFormats:
  Reveal:
    baseName: index
    mediaType: "text/html"
    isHTML: true

taxonomies:
  categories: categories
  series: series
  tag: tags

caches:
  assets:
    dir: :resourceDir/_gen
    maxAge: 3600s
  getcsv:
    dir: :cacheDir/:project
    maxAge: 3600s
  getjson:
    dir: :cacheDir/:project
    maxAge: 3600s
  getresource:
    dir: :cacheDir/:project
    maxAge: 3600s
  images:
    dir: :resourceDir/_gen
    maxAge: 3600s
  modules:
    dir: :cacheDir/modules
    maxAge: 3600s
