---
baseURL: "https://CasaRuralIsabel.com"
title: Web de Casa Rural Isabel
theme: gohugo-theme-ananke

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
GoogleAnalytics: false

relativeURLs: true

minify:
  disableXML: true
  minifyOutput: true

pagination:
  pagerSize: 5

params:
  mainSections: [blog]
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Casa Rural Isabel
  # description: ""
  keywords: [Blog]
  author: Casa Rural Isabel
  # author: ["Me", "You"] # multiple authors
  images: []
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  responsiveImages: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  searchHidden: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    disableFingerprinting: true

  label:
    text: "Home"
    icon: /apple-icon-152x152.png
    iconHeight: 35

menu:
  main:
    - identifier: home
      name: 🏠 Inicio
      url: /
      weight: 10
    - identifier: About
      name: 🗒️La casa
      url: /about/
      weight: 15

outputs:
  home: ["HTML", "RSS"]
  page: ["HTML"]

sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"
  priority: 0.5

permalinks:
  posts: /:year/:month/:day/:title/
  /: /:year/:month/:day/:title/
  blog: /blog/:year/:month/:day/:title/

taxonomies:
  categories: categories
  series: series
  tag: tags
